#pragma once
// Auto-generated by offsets.win

#include <cstdint>

namespace Decryptions
{
	namespace BaseNetworkable_Decryption
	{
		// decryptions::base_networkable_one
		std::uintptr_t base_networkable_one(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::base_networkable_two
		std::uintptr_t base_networkable_two(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xF651832Au;
		        eax = eax + 0x87D72C46u;
		        eax = (eax << 0x04) | (eax >> 0x1C);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace ActiveItem_Decryption
	{
		// decryptions::decrypt_active_item
		std::uintptr_t decrypt_active_item(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x606ABD8Eu;
		        eax = eax + 0xE5A5F712u;
		        eax = (eax << 0x1F) | (eax >> 0x01);
		        eax = eax + 0x2CEDCC8Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_PlayerEyes
		std::uintptr_t decrypt_PlayerEyes(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1655CA51u;
		        eax = eax ^ 0x31618264u;
		        eax = (eax << 0x1B) | (eax >> 0x05);
		        eax = eax ^ 0xCBF8ABEAu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_0x5C8
		std::uintptr_t decrypt_0x5C8(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x12) | (eax << 0x0E);
		        eax = eax + 0xE6C79BEu;
		        eax = eax ^ 0xF10E3369u;
		        eax = (eax << 0x1D) | (eax >> 0x03);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_playerFlags
		std::uintptr_t decrypt_playerFlags(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xC25D65A0u;
		        eax = (eax << 0x10) | (eax >> 0x10);
		        eax = eax ^ 0x697ED018u;
		        eax = (eax << 0x05) | (eax >> 0x1B);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_playerFlags_2
		std::uintptr_t decrypt_playerFlags_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0xF677EDDEu;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        eax = eax ^ 0xE1218090u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_ulong
		std::uintptr_t decrypt_ulong(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xC75E49E4u;
		        eax = (eax << 0x08) | (eax >> 0x18);
		        eax = eax - 0x6A76CBD6u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt
		std::uintptr_t decrypt(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x05) | (eax << 0x1B);
		        eax = eax ^ 0x37C09A5Au;
		        eax = eax + 0x7071715Au;
		        eax = eax ^ 0xB15E6650u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_2
		std::uintptr_t decrypt_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1F8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_3
		std::uintptr_t decrypt_3(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x3E9FCE7Au;
		        eax = (eax << 0x09) | (eax >> 0x17);
		        eax = eax - 0x5B031F93u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_4
		std::uintptr_t decrypt_4(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xD6899709u;
		        eax = (eax << 0x11) | (eax >> 0x0F);
		        eax = eax + 0x528283C0u;
		        eax = (eax << 0x0F) | (eax >> 0x11);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace PlayerInventory_Decryption
	{
		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0xF677EDDEu;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        eax = eax ^ 0xE1218090u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace Convar_Graphics_Decryption
	{
		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1B) | (eax << 0x05);
		        eax = eax + 0x76C9D570u;
		        eax = (eax << 0x0F) | (eax >> 0x11);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_int_2
		std::uintptr_t decrypt_int_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x369469B5u;
		        eax = eax ^ 0xB9E6799u;
		        eax = (eax << 0x10) | (eax >> 0x10);
		        eax = eax ^ 0xE64F07D9u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::fov
		uint64_t encrypt_fov(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x58B9B682u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}


		uint32_t decrypt_fov(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax + 0x58B9B682u;
		    return eax;
		}

	}

	namespace Convar_Admin_Decryption
	{
		// decryptions::decrypt_float
		std::uintptr_t decrypt_float(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x58B9B682u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}


		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax + 0x58B9B682u;
		    return eax;
		}

	}

	namespace Convar_Server_Decryption
	{
		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax ^ 0x461DC88u;
		    eax = eax + 0x5C3DF674u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}


		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x5C3DF674u;
		    eax = eax ^ 0x461DC88u;
		    return eax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x2D5D40B8u;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax + 0x9282B7EBu;
		        eax = (eax << 0x1B) | (eax >> 0x05);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		uint64_t encrypt_0xFC(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax ^ 0xDF381FC5u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_0xFC(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax ^ 0xDF381FC5u;
		    return eax;
		}

	}

	namespace BaseProjectile_Decryption
	{
		// decryptions::decrypt_aimCone
		std::uintptr_t decrypt_aimCone(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x04) | (eax << 0x1C);
		        eax = eax + 0x59CE9F1Au;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_recoil
		std::uintptr_t decrypt_recoil(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x11) | (eax << 0x0F);
		        eax = eax + 0x69E2E80u;
		        eax = (eax << 0x09) | (eax >> 0x17);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_2
		uint64_t encrypt_decrypt_2(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x59CE9F1Au;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}


		uint32_t decrypt_decrypt_2(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x59CE9F1Au;
		    return eax;
		}

	}

	namespace PlayerInput_Decryption
	{
		// decryptions::decrypt_state
		std::uintptr_t decrypt_state(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_buttons
		std::uintptr_t decrypt_buttons(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x606ABD8Eu;
		        eax = eax + 0xE5A5F712u;
		        eax = (eax << 0x1F) | (eax >> 0x01);
		        eax = eax + 0x2CEDCC8Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_aimAngles
		std::uintptr_t decrypt_aimAngles(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0xF677EDDEu;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        eax = eax ^ 0xE1218090u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_3
		std::uintptr_t decrypt_3(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0B) | (eax << 0x15);
		        eax = eax - 0x2118533Au;
		        eax = eax ^ 0x59BB0A2Au;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_4
		uint64_t encrypt_decrypt_4(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = ~eax;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}


		uint32_t decrypt_decrypt_4(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = ~eax;
		    return eax;
		}

		// decryptions::decrypt_5
		std::uintptr_t decrypt_5(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1655CA51u;
		        eax = eax ^ 0x31618264u;
		        eax = (eax << 0x1B) | (eax >> 0x05);
		        eax = eax ^ 0xCBF8ABEAu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace HeldEntity_Decryption
	{
		// decryptions::decrypt_viewModel
		std::uintptr_t decrypt_viewModel(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0xF677EDDEu;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        eax = eax ^ 0xE1218090u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_nextAttackTime
		std::uintptr_t decrypt_nextAttackTime(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_hostileScore
		std::uintptr_t decrypt_hostileScore(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0B) | (eax << 0x15);
		        eax = eax - 0x2118533Au;
		        eax = eax ^ 0x59BB0A2Au;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}


		// decryptions::decrypt_parentEntity
		std::uintptr_t decrypt_parentEntity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}


	namespace AutoTurret_Decryption
	{
		// decryptions::decrypt_target
		std::uintptr_t decrypt_target(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xC75E49E4u;
		        eax = (eax << 0x08) | (eax >> 0x18);
		        eax = eax - 0x6A76CBD6u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_sightRange
		std::uintptr_t decrypt_sightRange(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace PlayerWalkMovement_Decryption
	{
		// decryptions::decrypt_groundAngle
		std::uintptr_t decrypt_groundAngle(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x606ABD8Eu;
		        eax = eax + 0xE5A5F712u;
		        eax = (eax << 0x1F) | (eax >> 0x01);
		        eax = eax + 0x2CEDCC8Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_groundVelocity
		std::uintptr_t decrypt_groundVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x03) | (eax << 0x1D);
		        eax = eax + 0xE1E21F8Du;
		        eax = (eax << 0x08) | (eax >> 0x18);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_maxVelocity
		std::uintptr_t decrypt_maxVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0B) | (eax << 0x15);
		        eax = eax + 0x1D0D6939u;
		        eax = (eax << 0x0E) | (eax >> 0x12);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace BuildingPrivlidge_Decryption
	{
		// decryptions::decrypt_upkeep
		std::uintptr_t decrypt_upkeep(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x1E7771Eu;
		        eax = (eax << 0x06) | (eax >> 0x1A);
		        eax = eax - 0x1118D90Cu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_authorizedPlayers
		std::uintptr_t decrypt_authorizedPlayers(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xC75E49E4u;
		        eax = (eax << 0x08) | (eax >> 0x18);
		        eax = eax - 0x6A76CBD6u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_protectedMinutes
		std::uintptr_t decrypt_protectedMinutes(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0xF677EDDEu;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        eax = eax ^ 0xE1218090u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

}
