#pragma once
// Auto-generated by RustDumper
// Do not edit — re-run dumper to update

#include <cstdint>

namespace Decryptions
{
	namespace BaseNetworkable_Decryption
	{
		// decryptions::base_networkable_one
		std::uintptr_t base_networkable_one(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xF52DDF5Eu;
		        eax = (eax << 0x1E) | (eax >> 0x02);
		        eax = eax - 0x1C883CF3u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::base_networkable_two
		std::uintptr_t base_networkable_two(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x1C924BB9u;
		        eax = (eax << 0x1B) | (eax >> 0x05);
		        eax = eax + 0xDA3C33C9u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	} // namespace BaseNetworkable_Decryption

	namespace ActiveItem_Decryption
	{
		// decryptions::decrypt_active_item
		std::uintptr_t decrypt_active_item(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x02) | (eax << 0x1E);
		        eax = eax + 0x33CA3440u;
		        eax = (eax << 0x0D) | (eax >> 0x13);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_PlayerEyes
		std::uintptr_t decrypt_PlayerEyes(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x36AF9044u;
		        eax = (eax << 0x18) | (eax >> 0x08);
		        eax = eax + 0xE69F3211u;
		        eax = (eax << 0x1B) | (eax >> 0x05);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_ulong
		std::uintptr_t decrypt_ulong(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x5A5C4125u;
		        eax = eax ^ 0xC4252FBAu;
		        eax = (eax << 0x0B) | (eax >> 0x15);
		        eax = eax + 0x55E87293u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_float
		std::uintptr_t decrypt_float(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x3B6F7589u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x4A51A203u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x03) | (eax << 0x1D);
		        eax = eax ^ 0xE60CEE42u;
		        eax = (eax << 0x19) | (eax >> 0x07);
		        eax = eax + 0x5A393770u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt
		std::uintptr_t decrypt(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax - 0x7E5E243Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_2
		std::uintptr_t decrypt_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1D) | (eax << 0x03);
		        eax = eax + 0x29FC857Au;
		        eax = eax ^ 0x9846C0u;
		        eax = eax + 0x730C9256u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	} // namespace ActiveItem_Decryption

	namespace PlayerInventory_Decryption
	{
		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x03) | (eax << 0x1D);
		        eax = eax ^ 0xE60CEE42u;
		        eax = (eax << 0x19) | (eax >> 0x07);
		        eax = eax + 0x5A393770u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	} // namespace PlayerInventory_Decryption

	namespace Convar_Graphics_Decryption
	{
		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xF52DDF5Eu;
		        eax = (eax << 0x1E) | (eax >> 0x02);
		        eax = eax - 0x1C883CF3u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x08) | (eax << 0x18);
		        eax = eax + 0x4057FE99u;
		        eax = (eax << 0x1F) | (eax >> 0x01);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::fov
		uint64_t encrypt_fov(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0x384E1EDFu;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_fov(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x384E1EDFu;
		    return eax;
		}

		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax - 0xE1C8AEAu;
		    eax = eax ^ 0xD77D889Cu;
		    eax = (eax << 0x1D) | (eax >> 0x03);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x1D) | (eax << 0x03);
		    eax = eax ^ 0xD77D889Cu;
		    eax = eax + 0xE1C8AEAu;
		    return eax;
		}

	} // namespace Convar_Graphics_Decryption

	namespace Convar_Admin_Decryption
	{
		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x5B9366D8u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x5B9366D8u;
		    return eax;
		}

		// decryptions::decrypt_float
		std::uintptr_t decrypt_float(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xF52DDF5Eu;
		        eax = (eax << 0x1E) | (eax >> 0x02);
		        eax = eax - 0x1C883CF3u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xB5C35EF2u;
		        eax = (eax << 0x18) | (eax >> 0x08);
		        eax = eax + 0xEEF6DAACu;
		        eax = (eax << 0x14) | (eax >> 0x0C);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	} // namespace Convar_Admin_Decryption

	namespace Convar_Server_Decryption
	{
		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax - 0x6450E18Au;
		    eax = (eax >> 0x12) | (eax << 0x0E);
		    eax = eax - 0x44FC63A3u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax + 0x44FC63A3u;
		    eax = (eax << 0x12) | (eax >> 0x0E);
		    eax = eax + 0x6450E18Au;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    return eax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xF52DDF5Eu;
		        eax = (eax << 0x1E) | (eax >> 0x02);
		        eax = eax - 0x1C883CF3u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0xAD4073E7u;
		        eax = (eax << 0x08) | (eax >> 0x18);
		        eax = eax ^ 0x3B937F0Eu;
		        eax = (eax << 0x09) | (eax >> 0x17);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		std::uintptr_t decrypt_int(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x70u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

		// decryptions::decrypt_int
		uint64_t encrypt_decrypt_int(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = eax + 0x1u;
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_int(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = eax - 0x1u;
		    return eax;
		}

	} // namespace Convar_Server_Decryption

	namespace BaseProjectile_Decryption
	{
		// decryptions::decrypt_aimCone
		std::uintptr_t decrypt_aimCone(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0x34A2FB74u;
		        eax = eax ^ 0xEF51908Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	} // namespace BaseProjectile_Decryption

} // namespace Decryptions
