#pragma once
// Auto-generated by offsets.win

#include <cstdint>

namespace Decryptions
{
	namespace BaseNetworkable_Decryption
	{
		// decryptions::base_networkable_one
		std::uintptr_t base_networkable_one(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::base_networkable_two
		std::uintptr_t base_networkable_two(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0x151DA616u;
		        eax = (eax << 0x10) | (eax >> 0x10);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace ActiveItem_Decryption
	{
		// decryptions::decrypt_active_item
		std::uintptr_t decrypt_active_item(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x69E0F77u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax ^ 0xDE2AC61Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_0xE0
		std::uintptr_t decrypt_0xE0(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x19) | (eax << 0x07);
		        eax = eax + 0x8C16D8A4u;
		        eax = (eax << 0x15) | (eax >> 0x0B);
		        eax = eax ^ 0x295124D3u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}



		// decryptions::decrypt_GestureConfig
		std::uintptr_t decrypt_GestureConfig(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_float
		std::uintptr_t decrypt_float(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x3;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0x9D7C7E29u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x4B9A3504u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_playerFlags
		std::uintptr_t decrypt_playerFlags(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xD5508AC5u;
		        eax = eax + 0xD525B4F3u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x6823EB73u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_ulong
		std::uintptr_t decrypt_ulong(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1D) | (eax << 0x03);
		        eax = eax ^ 0x8530F70Fu;
		        eax = eax + 0x3356569Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt
		std::uintptr_t decrypt(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x07) | (eax << 0x19);
		        eax = eax + 0x6C498D4Au;
		        eax = eax ^ 0xB9CF74B8u;
		        eax = eax - 0x5CC965Au;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_2
		std::uintptr_t decrypt_2(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0A) | (eax << 0x16);
		        eax = eax - 0x4A572E6Eu;
		        eax = eax ^ 0x4F5C9051u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerInventory_Decryption
	{
		// decryptions::decrypt_PlayerInventory
		std::uintptr_t decrypt_PlayerInventory(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace Convar_Graphics_Decryption
	{
		std::uintptr_t decrypt_0x18(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x5DCD7632u;
		        eax = (eax << 0x05) | (eax >> 0x1B);
		        eax = eax ^ 0x5145F227u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::fov
		uint64_t encrypt_fov(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax - 0x63398D63u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_fov(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax + 0x63398D63u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    return eax;
		}



	namespace Convar_Admin_Decryption
	{


		std::uintptr_t decrypt_0x18(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x03) | (eax << 0x1D);
		        eax = eax ^ 0xC54AD1C2u;
		        eax = eax + 0x3F664081u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


		// decryptions::decrypt_float
		uint64_t encrypt_decrypt_float(uint32_t a1)
		{
		    uint64_t v1;
		    uint32_t eax = a1;
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax - 0x63398D63u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    *(uint32_t*)&v1 = eax;
		    return v1;
		}

		uint32_t decrypt_decrypt_float(uint64_t a1)
		{
		    uint32_t eax = static_cast<uint32_t>(a1);
		    eax = (eax >> 0x19) | (eax << 0x07);
		    eax = eax + 0x63398D63u;
		    eax = (eax << 0x19) | (eax >> 0x07);
		    return eax;
		}

	}

	namespace Convar_Server_Decryption
	{
		// decryptions::decrypt_bool
		std::uintptr_t decrypt_bool(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	}

	namespace BaseProjectile_Decryption
	{
		// decryptions::decrypt_aimCone
		std::uintptr_t decrypt_aimCone(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x8A298AEAu;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x73B78A44u;
		        eax = eax ^ 0xE356AF56u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BaseCombatEntity_Decryption
	{
		// decryptions::decrypt_health
		std::uintptr_t decrypt_health(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x69E0F77u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax ^ 0xDE2AC61Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerInput_Decryption
	{
		// decryptions::decrypt_state
		std::uintptr_t decrypt_state(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_buttons
		std::uintptr_t decrypt_buttons(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x69E0F77u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax ^ 0xDE2AC61Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_aimAngles
		std::uintptr_t decrypt_aimAngles(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax ^ 0xD5508AC5u;
		        eax = eax + 0xD525B4F3u;
		        eax = (eax << 0x07) | (eax >> 0x19);
		        eax = eax + 0x6823EB73u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace HeldEntity_Decryption
	{
		// decryptions::decrypt_viewModel
		std::uintptr_t decrypt_viewModel(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_nextAttackTime
		std::uintptr_t decrypt_nextAttackTime(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x19) | (eax << 0x07);
		        eax = eax + 0x63398D63u;
		        eax = (eax << 0x19) | (eax >> 0x07);
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_hostileScore
		std::uintptr_t decrypt_hostileScore(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BaseEntity_Decryption
	{
		// decryptions::decrypt_flags
		std::uintptr_t decrypt_flags(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}


	namespace AutoTurret_Decryption
	{
		// decryptions::decrypt_target
		std::uintptr_t decrypt_target(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax - 0x262EB439u;
		        eax = eax ^ 0xCA26D0E8u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_sightRange
		std::uintptr_t decrypt_sightRange(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x0E) | (eax << 0x12);
		        eax = eax + 0x97ACC028u;
		        eax = (eax << 0x0C) | (eax >> 0x14);
		        eax = eax + 0x12C55E8Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_aimCone
		std::uintptr_t decrypt_aimCone(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1D) | (eax << 0x03);
		        eax = eax ^ 0x8530F70Fu;
		        eax = eax + 0x3356569Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace PlayerWalkMovement_Decryption
	{
		// decryptions::decrypt_groundAngle
		std::uintptr_t decrypt_groundAngle(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x1;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x09) | (eax << 0x17);
		        eax = eax ^ 0x1ADB037Au;
		        eax = eax - 0x6A1E293u;
		        eax = eax ^ 0xF1F22894u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_groundVelocity
		std::uintptr_t decrypt_groundVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x69E0F77u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax ^ 0xDE2AC61Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_maxVelocity
		std::uintptr_t decrypt_maxVelocity(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x13) | (eax << 0x0D);
		        eax = eax + 0x50DCA37Fu;
		        eax = eax ^ 0x7DA4B534u;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

	namespace BuildingPrivlidge_Decryption
	{
		// decryptions::decrypt_upkeep
		std::uintptr_t decrypt_upkeep(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = eax + 0x69E0F77u;
		        eax = (eax << 0x1C) | (eax >> 0x04);
		        eax = eax ^ 0xDE2AC61Bu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

		// decryptions::decrypt_authorizedPlayers
		std::uintptr_t decrypt_authorizedPlayers(std::uintptr_t a1)
		{
		    std::uintptr_t rax = a1;
		    std::uintptr_t* rdx = &rax;
		    std::uint32_t r8d = 0x2;
		    uint32_t eax, ecx;
		
		    do {
		        eax = *(std::uint32_t*)(rdx);
		        rdx = (std::uintptr_t*)((std::uint8_t*)rdx + 0x4);
		        eax = (eax >> 0x1D) | (eax << 0x03);
		        eax = eax ^ 0x8530F70Fu;
		        eax = eax + 0x3356569Eu;
		        *((std::uint32_t*)rdx - 1) = eax;
		        --r8d;
		    } while (r8d);
		    return rax;
		}

	}

}
