#pragma once
// Auto-generated by offsets.win

#include <cstdint>

namespace Offsets
{
	namespace BasePlayer
	{
		constexpr auto playerNames                             = 0x668;
		constexpr auto PlayerEyes                              = 0x2c8;
		constexpr auto PlayerInventory                         = 0x300;
		constexpr auto PlayerInput                             = 0x700;
		constexpr auto PlayerMovement                          = 0x4a0;
		constexpr auto PlayerModel                             = 0x500;
		constexpr auto playerFlags                             = 0x630;
		constexpr auto ModelState                              = 0x5c8;
		constexpr auto currentTeam                             = 0x4b8;
		constexpr auto clActiveItem                            = 0x4e8;
		constexpr auto clothingBlocksAiming                    = 0x714;
		constexpr auto clothingMoveSpeedReduction              = 0x718;
		constexpr auto UserID                                  = 0x4d8;
		constexpr auto metabolism                              = 0x588;
		constexpr auto modifiers                               = 0x2a8;
		constexpr auto clothingAccuracyBonus                   = 0x720;
		constexpr auto clothingWaterSpeedBonus                 = 0x71c;
	}

	namespace BaseEntity
	{
		constexpr auto model                                   = 0xf0;
		constexpr auto Bounds                                  = 0xc8;
		constexpr auto flags                                   = 0xf8;
		constexpr auto skinID                                  = 0x100;
		constexpr auto triggers                                = 0x190;
		constexpr auto HasBrain                                = 0x110;
		constexpr auto gameObject                              = 0xe0;
	}

	namespace BaseCombatEntity
	{
		constexpr auto LifeState                               = 0x270;
		constexpr auto _health                                 = 0x278;
		constexpr auto _maxHealth                              = 0x27c;
		constexpr auto startHealth                             = 0x208;
		constexpr auto skeletonProperties                      = 0x1f8;
		constexpr auto baseProtection                          = 0x200;
		constexpr auto ShowHealthInfo                          = 0x268;
	}

	namespace PlayerModel
	{
		constexpr auto Position                                = 0x1f8;
		constexpr auto Velocity                                = 0x204;
		constexpr auto newVelocity                             = 0x210;
		constexpr auto Rotation                                = 0x228;
		constexpr auto GestureConfig                           = 0x370;
		constexpr auto IsNpc__BackingField                     = 0x4c4;
		constexpr auto __Multimesh                             = 0x1f0;
	}

	// ItemContainer real: %f17b0f7dcd18fec1d35b1eaf171b45dc8327ea69
	namespace PlayerInventory
	{
		constexpr auto ItemContainer                           = 0x28;
		constexpr auto ContainerBelt                           = 0x30;
		constexpr auto ContainerWear                           = 0x78;
	}

	// real: %646dec92f2e0392452ad1db4f4eede646e78dad9
	namespace Item
	{
		constexpr auto ItemList                                = 0x40;
		constexpr auto ItemDefinition                          = 0x48;
		constexpr auto Amount                                  = 0x20;
		constexpr auto CurrentHealth                           = 0x14;
		constexpr auto MaxHealth                               = 0xd0;
		constexpr auto ItemUID                                 = 0xc8;
		constexpr auto HeldEntity                              = 0x58;
	}

	// real: %f17b0f7dcd18fec1d35b1eaf171b45dc8327ea69
	namespace ItemContainer
	{
		constexpr auto ItemList                                = 0x60;
		constexpr auto Capacity                                = 0x38;
	}

	namespace List
	{
		constexpr auto Buffer                                  = 0x10;
		constexpr auto Count                                   = 0x18;
		constexpr auto ArrayBase                               = 0x20;
	}

	namespace HeldEntity
	{
		constexpr auto ViewModel                               = 0x268;
		constexpr auto viewModel                               = 0x278;
		constexpr auto hostileScore                            = 0x244;
	}

	namespace BaseViewModel
	{
		constexpr auto IronSights                              = 0x98;
		constexpr auto AnimationEvents                         = 0x80;
		constexpr auto ViewmodelBob                            = 0xd8;
		constexpr auto ViewmodelSway                           = 0x88;
		constexpr auto useViewModelCamera                      = 0x40;
		constexpr auto lazyaimRegular                          = 0x28;
	}

	namespace ItemDefinition
	{
		constexpr auto shortname                               = 0x28;
		constexpr auto itemid                                  = 0x20;
		constexpr auto displayName                             = 0x40;
		constexpr auto ItemMod                                 = 0x158;
		constexpr auto category                                = 0x58;
		constexpr auto rarity                                  = 0x90;
		constexpr auto stackable                               = 0x78;
		constexpr auto condition                               = 0xb8;
	}

	namespace Translate_Phrase
	{
		constexpr auto English                                 = 0x10;
	}

	namespace ItemModWearable
	{
		constexpr auto blocksAiming                            = 0x5c;
		constexpr auto occlusionType                           = 0x58;
	}

	namespace AttackEntity
	{
		constexpr auto repeatDelay                             = 0x294;
		constexpr auto deployDelay                             = 0x290;
		constexpr auto effectiveRange                          = 0x29c;
		constexpr auto npcDamageScale                          = 0x2a0;
		constexpr auto aiAimSwayOffset                         = 0x2b0;
		constexpr auto aiAimCone                               = 0x2b4;
		constexpr auto aiOnlyInRange                           = 0x2b8;
	}

	namespace BaseProjectile
	{
		constexpr auto reloadTime                              = 0x378;
		constexpr auto recoil                                  = 0x3a8;
		constexpr auto primaryMagazine                         = 0x380;
		constexpr auto aimconePenalty                          = 0x3f8;
		constexpr auto aimCone                                 = 0x3b8;
		constexpr auto aimconePenaltyPerShot                   = 0x3c0;
		constexpr auto aimSway                                 = 0x3a0;
		constexpr auto aimSwaySpeed                            = 0x3a4;
		constexpr auto stancePenaltyScale                      = 0x3d0;
		constexpr auto aimConePenaltyMax                       = 0x3c4;
		constexpr auto automatic                               = 0x338;
		constexpr auto hipAimCone                              = 0x3bc;
		constexpr auto isBurstWeapon                           = 0x3df;
		constexpr auto canChangeFireModes                      = 0x3e0;
		constexpr auto internalBurstFireRateScale              = 0x3e8;
		constexpr auto IsReloading                             = 0x45c;
		constexpr auto noAimingWhileCycling                    = 0x3d5;
		constexpr auto projectileVelocityScale                 = 0x334;
		constexpr auto turretDamageScale                       = 0x33c;
		constexpr auto damageScale                             = 0x32c;
		constexpr auto distanceScale                           = 0x330;
		constexpr auto aimconeCurve                            = 0x3b0;
	}

	namespace Projectile
	{
		constexpr auto initialVelocity                         = 0x28;
		constexpr auto thickness                               = 0x3c;
		constexpr auto velocity                                = 0x15c;
		constexpr auto position                                = 0x168;
		constexpr auto sentPosition                            = 0x180;
		constexpr auto previousPosition                        = 0x18c;
		constexpr auto previousVelocity                        = 0x198;
		constexpr auto projectileID                            = 0x20;
		constexpr auto owner                                   = 0x128;
		constexpr auto hitTest                                 = 0x118;
		constexpr auto drag                                    = 0x34;
		constexpr auto gravityModifier                         = 0x38;
		constexpr auto traveledDistance                        = 0x174;
		constexpr auto mod                                     = 0x110;
	}

	// real: %ab5bfbc425bffcd97b6699eb3ccd08ec637267f7
	namespace HitTest
	{
		constexpr auto HitTransform                            = 0x60;
		constexpr auto HitEntity                               = 0x10;
		constexpr auto type                                    = 0x18;
		constexpr auto Radius                                  = 0x44;
		constexpr auto didHit                                  = 0x28;
		constexpr auto HitNormal                               = 0x1c;
		constexpr auto HitPoint                                = 0x50;
		constexpr auto damageProperties                        = 0x70;
		constexpr auto HitDistance                             = 0x68;
		constexpr auto MultiHit                                = 0x29;
		constexpr auto attackRay                               = 0x2c;
		constexpr auto collider                                = 0x88;
		constexpr auto gameObject                              = 0xc0;
		constexpr auto Bone                                    = 0x60;
	}

	namespace RecoilProperties
	{
		constexpr auto recoilYawMin                            = 0x18;
		constexpr auto recoilYawMax                            = 0x1c;
		constexpr auto recoilPitchMin                          = 0x20;
		constexpr auto recoilPitchMax                          = 0x24;
		constexpr auto aimconeCurveScale                       = 0x60;
		constexpr auto newRecoilOverride                       = 0x80;
		constexpr auto timeToTakeMin                           = 0x28;
		constexpr auto timeToTakeMax                           = 0x2c;
		constexpr auto ADSScale                                = 0x30;
		constexpr auto movementPenalty                         = 0x34;
		constexpr auto clampPitch                              = 0x38;
		constexpr auto pitchCurve                              = 0x40;
		constexpr auto yawCurve                                = 0x48;
		constexpr auto shotsUntilMax                           = 0x54;
		constexpr auto maxRecoilRadius                         = 0x58;
	}

	namespace HackableLockedCrate
	{
		constexpr auto TimerText                               = 0x3d8;
	}

	namespace BuildingPrivlidge
	{
		constexpr auto UpkeepTime                              = 0x3cc;
		constexpr auto authorizedPlayers                       = 0x3c0;
	}

	namespace PatrolHelicopter
	{
		constexpr auto weakspots                               = 0x420;
		constexpr auto spotlightTarget                         = 0x3c8;
		constexpr auto maxCratesToSpawn                        = 0x358;
		constexpr auto bulletDamage                            = 0x360;
		constexpr auto bulletSpeed                             = 0x35c;
		constexpr auto myAI                                    = 0x438;
	}

	namespace CompoundBowWeapon
	{
		constexpr auto stringHoldDurationMax                   = 0x478;
		constexpr auto movementPenaltyRampUpTime               = 0x488;
	}

	namespace FlintStrikeWeapon
	{
		constexpr auto successFraction                         = 0x460;
		constexpr auto _didSparkThisFrame                      = 0x470;
	}

	namespace BowWeapon
	{
		constexpr auto attackReady                             = 0x470;
		constexpr auto nopullback                              = 0x464;
	}

	namespace SkinnedMultiMeshRenderers
	{
		constexpr auto Renderers__BackingField                 = 0x40;
	}

	namespace Model
	{
		constexpr auto bone_array                              = 0x50;
	}

	namespace ActiveItem
	{
		constexpr auto clActiveItem                            = 0x4e8;
	}

	namespace Magazine
	{
		constexpr auto definition                              = 0x20;
		constexpr auto capacity                                = 0x18;
		constexpr auto contents                                = 0x1c;
		constexpr auto ammoType                                = 0x20;
	}

	namespace PlayerEyes
	{
		constexpr auto bodyRotation                            = 0x50;
		constexpr auto viewOffset                              = 0x28;
		constexpr auto rotationLook                            = 0x6c;
	}

	namespace PlayerInput
	{
		constexpr auto state                                   = 0x28;
	}

	// real: %cc635d5fa753a0ffac59b1b4e63cf9f845795993
	namespace InputState
	{
		constexpr auto current                                 = 0x18;
		constexpr auto previous                                = 0x20;
	}

	// real: %4a61f8930700e60ffffb3af0e95e80b0b846ed75
	namespace InputMessage
	{
		constexpr auto buttons                                 = 0x20;
		constexpr auto aimAngles                               = 0x10;
		constexpr auto mouseDelta                              = 0x24;
	}

	namespace PlayerWalkMovement
	{
		constexpr auto groundAngle                             = 0x70;
		constexpr auto groundAngleNew                          = 0x78;
		constexpr auto capsule                                 = 0xf0;
		constexpr auto groundVelocity                          = 0x128;
		constexpr auto ladder                                  = 0xd8;
	}

	namespace BaseMelee
	{
		constexpr auto effectiveRange                          = 0x29c;
		constexpr auto attackRadius                            = 0x344;
		constexpr auto maxDistance                             = 0x340;
		constexpr auto gathering                               = 0x378;
		constexpr auto damageProperties                        = 0x328;
		constexpr auto canThrowAsProjectile                    = 0x381;
		constexpr auto aiStrikeDelay                           = 0x35c;
	}

	namespace FlameThrower
	{
		constexpr auto fuelPerSec                              = 0x398;
		constexpr auto flameRange                              = 0x340;
		constexpr auto ammo                                    = 0x32c;
	}

	namespace BaseMountable
	{
		constexpr auto mountedPlayer                           = 0x2a8;
		constexpr auto canWieldItems                           = 0x2e4;
		constexpr auto isMobile                                = 0x391;
		constexpr auto canDrinkWhileMounted                    = 0x380;
	}

	namespace AutoTurret
	{
		constexpr auto sightRange                              = 0x450;
		constexpr auto aimCone                                 = 0x4b0;
		constexpr auto targetTrigger                           = 0x4f0;
		constexpr auto target                                  = 0x418;
		constexpr auto bulletSpeed                             = 0x3c8;
	}

	namespace Recycler
	{
		constexpr auto recycleEfficiency                       = 0x398;
	}

	namespace Object
	{
		constexpr auto m_CachedPtr                             = 0x10;
	}

	namespace BaseNetworkable_Fields
	{
		constexpr auto prefabID                                = 0x30;
	}

	namespace IronSights
	{
		constexpr auto aimSway                                 = 0x28;
		constexpr auto aimSwaySpeed                            = 0x2c;
	}

	namespace SkeletonProperties
	{
		constexpr auto bones                                   = 0x20;
	}

	namespace ProtectionProperties
	{
		constexpr auto amounts                                 = 0x28;
	}

	namespace WorldItem
	{
		constexpr auto allowPickup                             = 0x1d8;
	}

	namespace CodeLock
	{
		constexpr auto hasCode                                 = 0x248;
		constexpr auto hasGuestCode                            = 0x258;
	}

	namespace StorageContainer
	{
		constexpr auto isLootable                              = 0x305;
		constexpr auto inventorySlots                          = 0x2f8;
		constexpr auto panelName                               = 0x308;
		constexpr auto onlyOneUser                             = 0x374;
	}

	namespace PlayerLoot
	{
		constexpr auto entitySource                            = 0x28;
		constexpr auto containers                              = 0x38;
	}

	namespace DroppedItemContainer
	{
		constexpr auto playerName                              = 0x2a8;
		constexpr auto playerSteamID                           = 0x2c0;
	}

	namespace ItemModProjectile
	{
		constexpr auto projectileVelocity                      = 0x40;
		constexpr auto projectileVelocitySpread                = 0x44;
		constexpr auto numProjectiles                          = 0x38;
		constexpr auto spread                                  = 0x3c;
		constexpr auto projectileObject                        = 0x20;
	}

	namespace ProjectileWeaponMod
	{
		constexpr auto sightAimConeScale                       = 0x1d8;
		constexpr auto sightAimConeOffset                      = 0x268;
		constexpr auto hipAimConeScale                         = 0x280;
		constexpr auto hipAimConeOffset                        = 0x288;
	}

	namespace Construction
	{
		constexpr auto canBypassBuildingPermission             = 0xc0;
	}

	namespace BuildingBlock
	{
		constexpr auto grade                                   = 0x330;
		constexpr auto blockDefinition                         = 0x2f8;
	}

	namespace GrowableEntity
	{
		constexpr auto Properties                              = 0x2f8;
	}

	namespace PlantProperties
	{
		constexpr auto WaterIntake                             = 0x54;
		constexpr auto MaxSeasons                              = 0x50;
	}

	namespace MedicalTool
	{
		constexpr auto healDurationSelf                        = 0x328;
		constexpr auto maxDistanceOther                        = 0x334;
	}

	namespace Chainsaw
	{
		constexpr auto fuelPerSec                              = 0x3d4;
		constexpr auto maxAmmo                                 = 0x3d8;
	}

	namespace SamSite
	{
		constexpr auto currentAimDir                           = 0x3b4;
		constexpr auto vehicleScanRadius                       = 0x3cc;
		constexpr auto staticRespawn                           = 0x3e8;
		constexpr auto projectileTest                          = 0x3d8;
	}

	namespace TimedExplosive
	{
		constexpr auto timerAmountMin                          = 0x1d8;
		constexpr auto timerAmountMax                          = 0x1dc;
		constexpr auto explosionRadius                         = 0x1e4;
		constexpr auto stickEffect                             = 0x210;
		constexpr auto damageTypes                             = 0x250;
	}

	namespace GrenadeWeapon
	{
		constexpr auto maxThrowVelocity                        = 0x330;
	}

	namespace ThrownWeapon
	{
		constexpr auto maxThrowVelocity                        = 0x330;
	}

	namespace ServerProjectile
	{
		constexpr auto speed                                   = 0x3c;
		constexpr auto gravityModifier                         = 0x38;
		constexpr auto drag                                    = 0x34;
	}

	namespace PlayerCorpse
	{
		constexpr auto buoyancy                                = 0x310;
		constexpr auto underwearSkin                           = 0x318;
	}

	namespace MapView
	{
		constexpr auto mapImage                                = 0x20;
		constexpr auto scrollRect                              = 0x40;
	}

	namespace Planner
	{
		constexpr auto CurrentConstruction                     = 0x2b8;
	}

	namespace GestureConfig
	{
		constexpr auto gestureId                               = 0x18;
		constexpr auto gestureCommand                          = 0x20;
		constexpr auto duration                                = 0x4c;
	}

	namespace BaseFishingRod
	{
		constexpr auto FishCatchDistance                       = 0x298;
		constexpr auto MaxCastDistance                         = 0x2d4;
	}

	namespace ColliderInfo
	{
		constexpr auto flags                                   = 0x20;
	}

	namespace PlayerMetabolism
	{
		constexpr auto temperature                             = 0x48;
		constexpr auto comfort                                 = 0x88;
		constexpr auto radiation_level                         = 0x58;
		constexpr auto radiation_poison                        = 0x60;
		constexpr auto bleeding                                = 0x80;
		constexpr auto oxygen                                  = 0x78;
		constexpr auto wetness                                 = 0x68;
		constexpr auto dirtyness                               = 0x70;
		constexpr auto pending_health                          = 0x90;
	}

	namespace MetabolismAttribute
	{
		constexpr auto value                                   = 0x20;
		constexpr auto min                                     = 0x18;
		constexpr auto max                                     = 0x1c;
		constexpr auto startMin                                = 0x10;
		constexpr auto startMax                                = 0x14;
	}

	namespace BaseMovement
	{
		constexpr auto Owner                                   = 0x28;
	}

	namespace LazyAimProperties
	{
		constexpr auto snapStrength                            = 0x18;
		constexpr auto deadzoneAngle                           = 0x1c;
	}

	namespace ViewmodelBob
	{
		constexpr auto bobSpeedWalk                            = 0x20;
		constexpr auto bobSpeedRun                             = 0x24;
		constexpr auto bobAmountWalk                           = 0x28;
		constexpr auto bobAmountRun                            = 0x2c;
	}

	namespace ViewmodelSway
	{
		constexpr auto positionalSwaySpeed                     = 0x20;
		constexpr auto positionalSwayAmount                    = 0x24;
		constexpr auto rotationSwaySpeed                       = 0x28;
		constexpr auto rotationSwayAmount                      = 0x2c;
	}

	namespace MotorRowboat
	{
		constexpr auto fuelPerSec                              = 0x510;
	}

	namespace HotAirBalloon
	{
		constexpr auto inflationLevel                          = 0x334;
		constexpr auto windForce                               = 0x38c;
		constexpr auto fuelPerSec                              = 0x340;
		constexpr auto liftAmount                              = 0x2d8;
	}

	namespace RidableHorse
	{
		constexpr auto staminaCoreLossRatio                    = 0x600;
	}

	namespace Snowmobile
	{
		constexpr auto engineKW                                = 0x510;
	}

	namespace TrainEngine
	{
		constexpr auto maxSpeed                                = 0x5c4;
	}

	namespace Kayak
	{
		constexpr auto maxPaddleFrequency                      = 0x478;
	}

	namespace BradleyAPC
	{
		constexpr auto health                                  = 0x2f0;
	}

	namespace SimpleShark
	{
		constexpr auto aggroRange                              = 0x2cc;
	}

	namespace Landmine
	{
		constexpr auto minExplosionRadius                      = 0x2f8;
	}

	namespace GunTrap
	{
		constexpr auto ammoType                                = 0x3b8;
	}

	namespace FlameTurret
	{
		constexpr auto arc                                     = 0x388;
		constexpr auto fuelPerSec                              = 0x398;
	}

	namespace TeslaCoil
	{
		constexpr auto maxDischargeSelfDamageSeconds           = 0x330;
		constexpr auto maxDamageOutput                         = 0x334;
		constexpr auto dischargeTickRate                       = 0x32c;
	}

	namespace Barricade
	{
		constexpr auto reflectDamage                           = 0x2e0;
	}

	namespace Door
	{
		constexpr auto canHandOpen                             = 0x33d;
	}

	namespace StabilityEntity
	{
		constexpr auto grounded                                = 0x2e0;
	}

	namespace BaseOven
	{
		constexpr auto temperature                             = 0x388;
		constexpr auto allowByproductCreation                  = 0x3d8;
	}

	namespace Workbench
	{
		constexpr auto Workbenchlevel                          = 0x38c;
	}

	namespace RepairBench
	{
		constexpr auto maxConditionLostOnRepair                = 0x380;
	}

	namespace ElectricalBranch
	{
		constexpr auto branchAmount                            = 0x320;
	}

	namespace VendingMachine
	{
		constexpr auto shopName                                = 0x3b8;
	}

	namespace LootContainer
	{
		constexpr auto maxDefinitionsToSpawn                   = 0x390;
		constexpr auto initialLootSpawn                        = 0x39c;
		constexpr auto scrapAmount                             = 0x3ac;
	}

	namespace SupplyDrop
	{
		constexpr auto parachute                               = 0x3d0;
	}

	namespace DroppedItem
	{
		constexpr auto itemModel                               = 0x1e8;
	}

	namespace TreeEntity
	{
		constexpr auto woodAmount                              = 0x224;
		constexpr auto fallDuration                            = 0x1f4;
	}

	namespace ResourceDispenser
	{
		constexpr auto containedItems                          = 0x38;
		constexpr auto gatherType                              = 0x30;
		constexpr auto fractionRemaining                       = 0x54;
		constexpr auto maxDestroyFractionForFinishBonus        = 0x40;
	}

	namespace MiningQuarry
	{
		constexpr auto processRate                             = 0x2d8;
		constexpr auto fuelStoragePrefab                       = 0x2e8;
	}

	namespace SleepingBag
	{
		constexpr auto niceName                                = 0x328;
		constexpr auto canBePublic                             = 0x341;
	}

	namespace DamageProperties
	{
		constexpr auto fallback                                = 0x20;
	}

	namespace FireBall
	{
		constexpr auto damagePerSecond                         = 0x204;
		constexpr auto radius                                  = 0x208;
		constexpr auto tickRate                                = 0x200;
	}

	namespace BaseHelicopter
	{
		constexpr auto rotorPivot                              = 0x408;
	}

	namespace CargoShip
	{
		constexpr auto targetNodeIndex                         = 0x1d8;
	}

	namespace ExcavatorArm
	{
		constexpr auto resourceProductionTickRate              = 0x250;
		constexpr auto timeForFullResources                    = 0x254;
	}

	namespace TOD_Sky_Fields
	{
		constexpr auto Day                                     = 0x58;
		constexpr auto Night                                   = 0x60;
		constexpr auto Cycle                                   = 0x40;
		constexpr auto Atmosphere                              = 0x50;
		constexpr auto Sun                                     = 0x68;
		constexpr auto Moon                                    = 0x70;
		constexpr auto Stars                                   = 0x78;
	}

	namespace TOD_CycleParameters
	{
		constexpr auto Hour                                    = 0x10;
		constexpr auto Day                                     = 0x14;
		constexpr auto Month                                   = 0x18;
		constexpr auto Year                                    = 0x1c;
	}

	namespace WaterBody
	{
		constexpr auto Type                                    = 0x20;
	}

	namespace Buoyancy
	{
		constexpr auto buoyancyScale                           = 0x38;
		constexpr auto doEffects                               = 0x3d;
	}

	namespace CCTV_RC
	{
		constexpr auto pitch                                   = 0x358;
		constexpr auto yaw                                     = 0x350;
	}

	namespace Telephone
	{
		constexpr auto Controller                              = 0x3d0;
	}

	namespace MapMarker
	{
		constexpr auto appType                                 = 0x1d8;
	}

	namespace BaseBoat
	{
		constexpr auto buoyancy                                = 0x410;
	}

	namespace ResearchTable
	{
		constexpr auto researchDuration                        = 0x388;
		constexpr auto researchCostFraction                    = 0x384;
	}

	namespace TriggerBase
	{
		constexpr auto interestLayers                          = 0x20;
		constexpr auto entityContents                          = 0x40;
	}

	namespace TriggerRadiation
	{
		constexpr auto RadiationAmountOverride                 = 0x54;
	}

	namespace WildlifeTrap
	{
		constexpr auto trapSuccessRate                         = 0x394;
		constexpr auto tickRate                                = 0x380;
	}

	namespace BaseNetworkable
	{
		constexpr auto ghandle                                 = 0xe4aaa90; // sig: "0D 88 55 80 0D E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto StaticFields                            = 0xb8;
		constexpr auto ClientEntities                          = 0x10;
		constexpr auto EntityList                              = 0x10;
		constexpr auto Buffer                                  = 0x18;
		constexpr auto ArrayBase                               = 0x20;
	}

	namespace ListComponent_Projectile
	{
		constexpr auto ListComponent_Projectile_C              = 0xe46a190; // sig: "F1 52 0D E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 6C B0 7B"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto instance                                = 0x28;
		constexpr auto instance_two                            = 0x18;
	}

	namespace TodSky
	{
		constexpr auto TodSky_C                                = 0xe4ef0d8; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 E8 ?? ?? ?? ?? 80 BB 44 02 00 00 00"
		constexpr auto Instance                                = 0x10;
	}

	namespace Convar_Admin
	{
		constexpr auto TypeInfo                                = 0xe4ccb70; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 82 B4 69 0D 01 33 D2 48 8B CB E8 6B"
	}

	namespace Convar_Graphics
	{
		constexpr auto TypeInfo                                = 0xe453bf8; // sig: "48 83 EC 20 80 3D 28 AC 47 0E 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 0B AC 47 0E 01 48 8B 05 ?? ?? ?? ??"
	}

	namespace Convar_Server
	{
		constexpr auto TypeInfo                                = 0xe49dfd8; // sig: "0D E8 ?? ?? ?? ?? 4B F9 A5 FF F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
	}

	namespace SingletonClimate
	{
		constexpr auto Climate_C                               = 0xe3fa998; // sig: "CC CC CC 48 83 EC 28 80 3D E3 6A 79 ?? 00 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 C9 6A 79 ?? 01 48 8B 05 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto Instance                                = 0x28;
	}

	namespace GameManager
	{
		constexpr auto Static_fields                           = 0xb8;
		constexpr auto client                                  = 0x10;
		constexpr auto Pool                                    = 0x20;
		constexpr auto Stack                                   = 0x18;
	}

	namespace ItemIcon
	{
		constexpr auto ItemIcon_C                              = 0xe453f18; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 04 2E 96 0B 01 48 8B 0D ?? ?? ?? ??"
		constexpr auto Static_fields                           = 0xc0;
		constexpr auto Instance                                = 0x18;
	}

	namespace PlayerEyes_Static
	{
		constexpr auto PlayerEyes_C                            = 0xe4cad60; // sig: "60 80 3D 15 F7 65 0D 00 48 8B FA 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 F5 F6 65 0D 01 48 8B 05 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace BasePlayer_Static
	{
		constexpr auto BasePlayer_C                            = 0xe4cc9a8; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 45 1A 84 0D 01 33 C9 E8 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto visiblePlayerList                       = 0xf50;
	}

	namespace CameraUpdateHook_Static
	{
		constexpr auto CameraUpdateHook_C                      = 0xe45a3d8; // sig: "0D AA CE C8 0C E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace Planner_Static
	{
		constexpr auto Planner_C                               = 0xe4b1bd8; // sig: "48 83 EC 20 80 3D 3E C4 AD 0D 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 21 C4 AD 0D 01 48 8B 15 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace MapView_Static
	{
		constexpr auto MapView_C                               = 0xe451110; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 75 ?? 9C 0D 01 48 8B 05 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace CraftingQueue_Static
	{
		constexpr auto CraftingQueue_C                         = 0xe4ec0e0; // sig: "0D 23 7F ?? 0D E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 8B A6 3F 0D 01 33 C9 E8 30 A6 66"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace WaterSystem_Static
	{
		constexpr auto WaterSystem_C                           = 0xe411c28; // sig: "CC CC CC 48 83 EC 28 80 3D BC 12 D2 0C 00 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 A2 12 D2 0C 01 48 8B 05 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace BaseScreenShake_Static
	{
		constexpr auto BaseScreenShake_C                       = 0xe45f348; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 88 C7 AB 09 01 4C 8B 05 ?? ?? ?? ??"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace MainCamera
	{
		constexpr auto MainCamera_C                            = 0xe4bace8; // sig: "48 83 EC 20 80 3D 8D 2B 6C 0E 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83"
		constexpr auto mainCamera                              = 0x58;
		constexpr auto mainCameraTransform                     = 0x78;
	}

	namespace SingletonComponent_MainCamera
	{
		constexpr auto SingletonComponent_C                    = 0xe457d38; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 F2 7F ?? 0D 01 48 8B 9F E8 00 00 00"
		constexpr auto Instance                                = 0x10;
	}

	namespace LocalPlayer_Static
	{
		constexpr auto static_fields                           = 0xb8;
		constexpr auto Entity                                  = 0x148;
	}

	namespace Performance_Static
	{
		constexpr auto Performance_C                           = 0xe4cacb8; // sig: "0D AD EE 33 0D E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto fps                                     = 0x49c;
	}

	namespace Buttons_Static
	{
		constexpr auto static_fields                           = 0xb8;
	}

	namespace TOD_Sky_Static
	{
		constexpr auto TOD_Sky_C                               = 0xe4ef0d8; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 E8 ?? ?? ?? ?? 80 BB 44 02 00 00 00"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto Instance                                = 0x10;
	}

	namespace OcclusionCulling
	{
		constexpr auto OcclusionCulling_C                      = 0xe4d73c8; // sig: "0D 78 ?? 14 09 E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto static_fields                           = 0xb8;
	}

	namespace ModelState
	{
		constexpr auto Flags                                   = 0x68;
		constexpr auto WaterLevel                              = 0x60;
		constexpr auto Ducking                                 = 0x64;
	}

	namespace Camera
	{
		constexpr auto MainCamera_C                            = 0xe4bace8; // sig: "48 83 EC 20 80 3D 8D 2B 6C 0E 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83"
	}

	namespace Il2Cpp
	{
		constexpr auto sTypeInfoDefinitionTable                = 0xe7e3b20;
		constexpr auto Il2CppHandle                            = 0xe7df910;
	}

	namespace SceneManager
	{
		constexpr auto GetActiveScene                          = 0xbf21fc0;
	}

}
