#pragma once
// auto generated by @decamped few offsets r broken will fix later when i have pc :)

#include <cstdint>

namespace Offsets
{
	namespace BasePlayer
	{
		constexpr auto playerNames                             = 0x318;
		constexpr auto PlayerEyes                              = 0x658;
		constexpr auto PlayerInventory                         = 0x730;
		constexpr auto PlayerInput                             = 0x570;
		constexpr auto PlayerMovement                          = 0x310;
		constexpr auto PlayerModel                             = 0x2c0;
		constexpr auto playerFlags                             = 0x630;
		constexpr auto ModelState                              = 0x708;
		constexpr auto currentTeam                             = 0x4b8;
		constexpr auto clActiveItem                            = 0x4e8;
		constexpr auto clothingBlocksAiming                    = 0x714;
		constexpr auto clothingMoveSpeedReduction              = 0x718;
		constexpr auto UserID                                  = 0x4d8;
	}

	namespace BaseEntity
	{
		constexpr auto model                                   = 0xf0;
		constexpr auto Bounds                                  = 0xc8;
		constexpr auto flags                                   = 0xf8;
	}

	namespace BaseCombatEntity
	{
		constexpr auto LifeState                               = 0x270;
	}

	namespace PlayerModel
	{
		constexpr auto Position                                = 0x1f8;
		constexpr auto Velocity                                = 0x204;
		constexpr auto newVelocity                             = 0x210;
		constexpr auto Rotation                                = 0x228;
		constexpr auto GestureConfig                           = 0x168;
		constexpr auto IsNpc__BackingField                     = 0x4c4;
		constexpr auto __Multimesh                             = 0x280;
	}

	namespace PlayerInventory
	{
		constexpr auto ItemContainer                           = 0x30;
		constexpr auto ContainerBelt                           = 0x58;
		constexpr auto ContainerWear                           = 0x78;
	}

	namespace Item
	{
		constexpr auto ItemList                                = 0x10;
		constexpr auto ItemDefinition                          = 0x60;
		constexpr auto Amount                                  = 0x7c;
		constexpr auto CurrentHealth                           = 0x10;
		constexpr auto MaxHealth                               = 0x78;
		constexpr auto ItemUID                                 = 0xa0;
		constexpr auto HeldEntity                              = 0x68;
	}

	namespace HeldEntity
	{
		constexpr auto ViewModel                               = 0x278;
	}

	namespace BaseViewModel
	{
		constexpr auto IronSights                              = 0x98;
		constexpr auto AnimationEvents                         = 0xb8;
		constexpr auto ViewmodelBob                            = 0xf0;
		constexpr auto ViewmodelSway                           = 0xe8;
	}

	namespace ItemDefinition
	{
		constexpr auto shortname                               = 0x28;
		constexpr auto itemid                                  = 0x20;
		constexpr auto displayName                             = 0x40;
		constexpr auto ItemMod                                 = 0x148;
	}

	namespace Translate_Phrase
	{
		constexpr auto English                                 = 0x10;
	}

	namespace ItemModWearable
	{
		constexpr auto blocksAiming                            = 0x5c;
		constexpr auto occlusionType                           = 0x58;
	}

	namespace AttackEntity
	{
		constexpr auto repeatDelay                             = 0x294;
		constexpr auto deployDelay                             = 0x290;
	}

	namespace BaseProjectile
	{
		constexpr auto reloadTime                              = 0x378;
		constexpr auto recoil                                  = 0x3a8;
		constexpr auto primaryMagazine                         = 0x380;
		constexpr auto aimconePenalty                          = 0x3f8;
		constexpr auto aimCone                                 = 0x3b8;
		constexpr auto aimconePenaltyPerShot                   = 0x3c0;
		constexpr auto aimSway                                 = 0x3a0;
		constexpr auto aimSwaySpeed                            = 0x3a4;
		constexpr auto stancePenaltyScale                      = 0x3d0;
		constexpr auto aimConePenaltyMax                       = 0x3c4;
		constexpr auto automatic                               = 0x338;
		constexpr auto hipAimCone                              = 0x3bc;
		constexpr auto isBurstWeapon                           = 0x3df;
		constexpr auto canChangeFireModes                      = 0x3e0;
		constexpr auto internalBurstFireRateScale              = 0x3e8;
		constexpr auto IsReloading                             = 0x45c;
		constexpr auto noAimingWhileCycling                    = 0x3d5;
		constexpr auto projectileVelocityScale                 = 0x334;
		constexpr auto turretDamageScale                       = 0x33c;
		constexpr auto damageScale                             = 0x32c;
		constexpr auto distanceScale                           = 0x330;
		constexpr auto aimconeCurve                            = 0x3b0;
	}

	namespace Projectile
	{
		constexpr auto initialVelocity                         = 0x28;
		constexpr auto thickness                               = 0x3c;
		constexpr auto velocity                                = 0x15c;
		constexpr auto position                                = 0x168;
		constexpr auto sentPosition                            = 0x180;
		constexpr auto previousPosition                        = 0x18c;
		constexpr auto previousVelocity                        = 0x198;
		constexpr auto projectileID                            = 0x20;
		constexpr auto owner                                   = 0x118;
		constexpr auto hitTest                                 = 0x1d8;
		constexpr auto drag                                    = 0x34;
		constexpr auto gravityModifier                         = 0x38;
		constexpr auto tumbleSpeed                             = 0xcc;
		constexpr auto traveledDistance                        = 0x174;
		constexpr auto closeFlybyDistance                      = 0xc8;
	}

	namespace HitTest
	{
		constexpr auto HitTransform                            = 0x88;
		constexpr auto HitEntity                               = 0x48;
	}

	namespace RecoilProperties
	{
		constexpr auto recoilYawMin                            = 0x18;
		constexpr auto recoilYawMax                            = 0x1c;
		constexpr auto recoilPitchMin                          = 0x20;
		constexpr auto recoilPitchMax                          = 0x24;
		constexpr auto aimconeCurveScale                       = 0x60;
		constexpr auto newRecoilOverride                       = 0x80;
	}

	namespace HackableLockedCrate
	{
		constexpr auto TimerText                               = 0x3d8;
	}

	namespace BuildingPrivlidge
	{
		constexpr auto UpkeepTime                              = 0x3cc;
	}

	namespace PatrolHelicopter
	{
		constexpr auto weakspots                               = 0x418;
	}

	namespace CompoundBowWeapon
	{
		constexpr auto stringHoldDurationMax                   = 0x478;
		constexpr auto movementPenaltyRampUpTime               = 0x488;
	}

	namespace FlintStrikeWeapon
	{
		constexpr auto successFraction                         = 0x460;
		constexpr auto _didSparkThisFrame                      = 0x470;
	}

	namespace BowWeapon
	{
		constexpr auto attackReady                             = 0x470;
		constexpr auto nopullback                              = 0x464;
	}

	namespace SkinnedMultiMeshRenderers
	{
		constexpr auto Renderers__BackingField                 = 0x40;
	}

	namespace Model
	{
		constexpr auto bone_array                              = 0x50;
	}

	namespace ActiveItem
	{
		constexpr auto clActiveItem                            = 0x4e8;
	}

	namespace Magazine
	{
		constexpr auto definition                              = 0x20;
		constexpr auto capacity                                = 0x18;
		constexpr auto contents                                = 0x1c;
	}

	namespace PlayerEyes
	{
		constexpr auto bodyRotation                            = 0x50;
		constexpr auto viewOffset                              = 0x28;
		constexpr auto rotationLook                            = 0x6c;
	}

	namespace PlayerInput
	{
		constexpr auto state                                   = 0x28;
	}

	namespace InputState
	{
		constexpr auto current                                 = 0x10;
		constexpr auto previous                                = 0x20;
	}

	namespace InputMessage
	{
		constexpr auto buttons                                 = 0x0;
		constexpr auto aimAngles                               = 0x0;
		constexpr auto mouseDelta                              = 0x0;
	}

	namespace PlayerWalkMovement
	{
		constexpr auto groundAngle                             = 0x70;
		constexpr auto groundAngleNew                          = 0x78;
	}

	namespace BaseMelee
	{
		constexpr auto effectiveRange                          = 0x29c;
		constexpr auto attackRadius                            = 0x344;
		constexpr auto maxDistance                             = 0x340;
		constexpr auto gathering                               = 0x378;
	}

	namespace FlameThrower
	{
		constexpr auto fuelPerSec                              = 0x398;
		constexpr auto flameRange                              = 0x340;
		constexpr auto ammo                                    = 0x32c;
	}

	namespace BaseMountable
	{
		constexpr auto mountedPlayer                           = 0x2a8;
		constexpr auto canWieldItems                           = 0x2e4;
	}

	namespace AutoTurret
	{
		constexpr auto sightRange                              = 0x450;
		constexpr auto aimCone                                 = 0x4b0;
		constexpr auto targetTrigger                           = 0x4f0;
	}

	namespace Recycler
	{
		constexpr auto recycleEfficiency                       = 0x398;
	}

	namespace BaseNetworkable
	{
		constexpr auto BaseNetworkable_C                       = 0xe454bd0; // sig: "0D 5B 39 7E ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto wrapper_class_ptr                       = 0x20;
		constexpr auto parent_static_fields                    = 0x10;
		constexpr auto entity                                  = 0x10;
	}

	namespace ListComponent_Projectile
	{
		constexpr auto ListComponent_Projectile_C              = 0xe441178; // sig: "0D CC A6 EB ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto instance                                = 0x28;
		constexpr auto instance_two                            = 0x18;
	}

	namespace TodSky
	{
		constexpr auto TodSky_C                                = 0xe44d298; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 D1 EC F5 0D 01 48 8B 0D ?? ?? ?? ??"
		constexpr auto Instance                                = 0x10;
	}

	namespace Convar_Admin
	{
		constexpr auto TypeInfo                                = 0xe44d5f0; // sig: "0D 9E 4A 30 0C E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 9B 53 6E 0C 01 E8 ?? ?? ?? ?? 48"
	}

	namespace Convar_Graphics
	{
		constexpr auto TypeInfo                                = 0xe457bb0; // sig: "48 83 EC 20 80 3D 3B 6D 44 0E 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 1E 6D 44 0E 01 48 8B 05 ?? ?? ?? ??"
	}

	namespace Convar_Server
	{
		constexpr auto TypeInfo                                = 0xe454be0; // sig: "0D 5A 39 7E ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0"
	}

	namespace SingletonClimate
	{
		constexpr auto Climate_C                               = 0xe465260; // sig: "00 00 00 80 3D 72 ?? AD 0D 00 48 8B E9 ?? ?? ?? ?? 0D E4 8B 7A ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 33 2C AD 0D 01 8B 45 10 48 89 9C"
		constexpr auto static_fields                           = 0xb8;
		constexpr auto Instance                                = 0x28;
	}

	namespace GameManager
	{
		constexpr auto GameManager_C                           = 0xD744828;
		constexpr auto Static_fields                           = 0xb8;
		constexpr auto Instance                                = 0x30;
		constexpr auto Pool                                    = 0x20;
		constexpr auto Stack                                   = 0x18;
	}

	namespace ItemIcon
	{
		constexpr auto ItemIcon_C                              = 0xe3d6a60; // sig: "8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 C6 05 FB 29 0F 0A 01 48 8B 0D ?? ?? ?? ??"
		constexpr auto Static_fields                           = 0xc0;
		constexpr auto Instance                                = 0x18;
	}

	namespace ModelState
	{
		constexpr auto Flags                                   = 0x30;
		constexpr auto WaterLevel                              = 0x58;
		constexpr auto Ducking                                 = 0x5c;
	}

	namespace Camera
	{
		constexpr auto MainCamera_C                            = 0xe463a88; // sig: "48 83 EC 20 80 3D DD 72 ?? 0E 00 48 8B D9 75 ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83 0C 24 00 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? F0 83"
	}

	namespace Il2Cpp
	{
		constexpr auto sTypeInfoDefinitionTable                = 0xe7ac9d8;
	}

	namespace SceneManager
	{
		constexpr auto GetActiveScene                          = 0xbef7fe0;
	}

} // namespace Offsets
